---
name: Docker Build and Deploy
on:
  workflow_call:
    secrets:
      bitbucketSSHKey:
        required: true
      sshKey:
        required: true
      awsRegion:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.bitbucketSSHKey }}
            ${{ secrets.sshKey }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ secrets.awsRegion }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.1

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV # Replaced set-output

      - name: Version
        id: version
        run: echo "VERSION=${GITHUB_REF##*/}-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Docker tags
        id: docker_tags
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_REPOSITORY="${DOCKER_REGISTRY}/${GITHUB_REPOSITORY,,}"
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            TAGS="${DOCKER_REPOSITORY}:${GITHUB_REF##*/}-${TIMESTAMP}-${GITHUB_SHA}"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAGS="${DOCKER_REPOSITORY}:${GITHUB_REF##*/}"
          fi
          echo "DOCKER_TAGS=${TAGS}" >> $GITHUB_ENV
        shell: bash

      - name: Set docker push
        run: |
          echo "DOCKER_PUSH=--push" >>$GITHUB_ENV
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64

      - name: Build (and push)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_TAGS }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            VERSION=${{ env.VERSION }}
          ssh: default=${{ env.SSH_AUTH_SOCK }}
        if: env.DOCKER_TAGS != ''
